version: '3'
services:
    influx-db:
        container_name: influx-database
        image: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes: 
            - ./influxDB:/var/lib/influxdb 
    grafana:
        container_name: grafana-container
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
