version: '3'
services:
    influx-db:
        container_name: influx-database
        image: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes: 
            - ./influxDB:/var/lib/influxdb 
    grafana:
        container_name: grafana-container
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        volumes: 
            - ./grafana:/var/lib/grafana
        logging:
            driver: none
    chronograf:
        container_name: chronograf-container
        image: quay.io/influxdb/chronograf:1.3.7.0
        ports:
            - "3001:8888"
        volumes: 
            - ./chronograf:/var/lib/chronograf
        logging:
            driver: none
    mongodb:
        container_name: mongodb-container
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes: 
            - ./mongoDB:/data/db                      
    influx-dump-server:
         depends_on:
           - influx-db
         build:
            context: ./server/
            dockerfile: Dockerfile
         container_name: influx-dump-server
         ports:
            - "8080:8080"   
         volumes:
            - ./server:/usr/src/app